### PR TITLE
Ww3

### PR DESCRIPTION
**Pull request by SBFRF**
implement ww3 functionality

### CODE REVIEW

**Comment by thesser1** [comment]
@SBFRF The setup cannot run without scanning the thredds server for save points.  Is there anything we can do to bypass this if we don't care about this step, or can you push the code to run this into the testbed repo?

**Comment by SBFRF** [comment]
I sent an email with specific info

------
Spicer Bak
Research Coastal Engineer 
Field Research Facility, Duck NC
Sent from my personal phone

On Jul 20, 2020, at 10:44 AM, Ty Hesser <notifications@github.com> wrote:

﻿
@SBFRF The setup cannot run without scanning the thredds server for save points. Is there anything we can do to bypass this if we don't care about this step, or can you push the code to run this into the testbed repo?

**Comment by SBFRF** [comment]
@thesser1  where do we stand on this?  I swear i merged these and others :-\

**Comment by SBFRF** [comment]
merged!

**Pull request merged**
